-- Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""system"" is not referenced");
with system;
pragma Warnings (On, "unit ""system"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



PACKAGE BASIC_SDL_DATAVIEW with SPARK_Mode
IS


SUBTYPE asn1SccMy_Integer is adaasn1rtl.Asn1UInt range 3 .. 1415;


function asn1SccMy_Integer_Equal(val1, val2: in asn1SccMy_Integer) return Boolean;

function asn1SccMy_Integer_Init return asn1SccMy_Integer;

ERR_MY_INTEGER:CONSTANT INTEGER := 1; 
FUNCTION asn1SccMy_Integer_IsConstraintValid(val : in asn1SccMy_Integer) return adaasn1rtl.ASN1_RESULT;
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide BASIC_SDL_DATAVIEW;


END BASIC_SDL_DATAVIEW;